export const LANGS = {
  ko: {
    exitTraining: "훈련장 나가기", survivorsLabel: "생존 인원", zoneLabel: "자기장",
    zoneWaiting: "대기 중", ammoFull: "탄약 가득", ammoLabel: "탄약", attack: "공격",
    zoneWarning: "자기장 밖입니다", matchupBtn: "상성표", matchupBtnClose: "상성표 닫기",
    matchupDesc: "가위바위보 상성 — 유리한 상대를 노려 승률을 높이세요!",
    muChar: "캐릭터", muAdv: "✅ 유리", muEven: "⚔ 경합", muDis: "❌ 불리",
    patchnotesBtn: "패치노트", patchnotesBtnClose: "패치노트 닫기",
    gameTitle: "해골천", welcomeMsg: "배틀로얄 전장에 오신 것을 환영합니다.",
    idLabel: "아이디", nicknameLabel: "닉네임", idPlaceholder: "최대 16자",
    nickPlaceholder: "최대 12자", enterBattle: "전장 입장",
    dailyLoginMsg: "오늘의 아이디를 입력하세요.", dailyIdPlaceholder: "아이디 입력",
    confirm: "확인", accountRecovery: "계정 문제 해결하기",
    season: "알파 시즌 3", charSelect: "캐릭터 선택", charCount: "캐릭터 7종",
    redDesc: "더블 펀치, 근접 압박형 탱커", greenDesc: "부메랑 4연발, 중거리 견제",
    blueDesc: "고속 저격, 긴 사거리",
    orangeDesc: "데미지 딜러, 폭발 분산 공격",
    controls: "WASD 이동 · 마우스 조준 · 클릭 공격 · 자동 장전",
    startBattle: "전투 시작", training: "훈련장", playAgain: "다시 시작", exit: "나가기",
    comingSoonDesc: "새 시즌 출시 예정",
    trophyLabel: "트로피", record: "{0}승 {1}패", winrate: "승률 {0}%  |  {1}승 / {2}판",
    firstGame: "첫 판에 도전하세요!", streak: "🔥 {0}연승 중",
    bestStreakLabel: "최고 연승: {0}",
    nextAmmo: "다음 탄 {0}s", noAmmo: "공격 불가", stability: "안정성 {0}%",
    doublePunch: "더블 펀치", boomerang: "부메랑", sniper: "고속 저격", bombAttack: "폭탄 투척",
    mapPrefix: "맵: ", resultKO: "전투 불능", trainingKO: "훈련 중 쓰러졌습니다.",
    dmgDealt: "입힌 데미지: {0}", rank1: "1위 🏆", rankN: "{0}위",
    resultDead: "전투 불능. {0} 트로피{1}", resultDraw: "무승부. {0} 트로피{1}",
    resultWin: "해골천의 최후의 1인! {0} 트로피{1}",
    resultLose: "{0}이(가) 우승했습니다. {1} 트로피{2}",
    streakAchieve: "🔥 {0}연승!{1}", streakBonus: " (+{0} 보너스)",
    streakBroken: "연승이 끊겼습니다 (최고: {0}연승)",
    milestone100: "🎉 100승 달성! +50 트로피\n",
    loginExceeded: "아이디 입력 횟수를 초과했습니다.",
    loginWrong: "아이디가 틀렸습니다.", loginRemain: "아이디가 틀렸습니다. 남은 시도: {0}회",
    myId: "내 아이디: {0}", totalTrophy: " (총 {0})",
    killFeed: "{0} 처치 -> {1}",
    zonePhase1: "1단계 축소", zonePhase2: "2단계 축소", zonePhase3: "3단계 축소",
    zonePhase4: "4단계 축소", zoneFinal: "최종 구역",
    loadingLights: "조명 생성 중...", loadingMap: "맵 생성 중...",
    loadingTraining: "훈련장 생성 중...", loadingInput: "입력 설정 중...",
    loadingReady: "준비 중...", loadingDone: "완료!",
    pv136a: "내 정보 + 리더보드 패널 추가", pv136b: "AI 랜덤 이름 (한글/영어/혼용)",
    pv136c: "리더보드 봇 유저 순위 표시", pv136d: "시즌별 승률 추가",
    pv136e: "알파 시즌 2 전환",
    pv136f: "Red HP 10000 → 9000, Green 사거리 5 → 6, Orange 폭탄속도 14 → 16",
    pv136g: "Green 부메랑 900 → 1100, Orange 분산 1000 → 400",
    pv136h: "Green 봇 AI 적정 교전 거리 3.5타일",
    pv135a: "Orange 분산 데미지 10 → 1000 버프", pv135b: "Orange 투사체 히트박스 2배 증가",
    pv135c: "Red 공격력 10% 증가 (4000 → 4400)", pv135d: "탄약 UI 미갱신 버그 수정",
    pv134a: "찹 우드 자기장 판정 제거", pv134b: "찹 우드 플레이어 이동 제한 해제",
    pv134c: "나무 체력 100 → 50", pv134d: "벌목 시간 2초 → 1초",
    pv133a: "모드 선택 UI 추가 (쇼다운/찹 우드 분기)",
    pv133b: "찹 우드 팀 구분 (머리 위 색상 마커 + 킬피드 색상)",
    pv133c: "Red 공격력 10% 증가 (4000 → 4400)",
    pv132a: "Orange 분산 사거리 5 → 2.5 너프", pv132b: "Red 이동속도 +4% 버프",
    pv132c: "Blue 공속 0.25 → 0.3초 너프", pv132d: "죽은 코드 정리 (-1400줄)",
    pv132e: "찹 우드 모드 스펙 작성",
    pv131a: "Orange 조준선 추가", pv131b: "상성표 4캐릭터로 갱신",
    pv131c: "3개 맵 자기장 밖 오브젝트 제거 + 경계 벽 추가",
    pv131d: "승리 시 결과 화면 안 뜨는 버그 수정", pv131e: "로비 UI 가로 25% 증가",
    pv131f: "LANGS 번역 데이터 모듈 분리", pv131g: "bestStreakLabel 번역 키 추가",
    pv130a: "Orange 캐릭터 정식 추가 (폭탄 + 5갈래 폭발)",
    pv130b: "자기장 색상 초록으로 변경", pv130c: "자기장 축소 시간 단축 (136초 → 75초)",
    pv130d: "받은 데미지 빨간 팝업 표시", pv130e: "Orange 사거리 8타일로 조정",
    pv129a: "봇 AI 개선 (타겟 선택, 자기장 인식, 캐릭터별 전략)",
    pv129b: "수풀 전투 발각 시스템 (공격/피격 시 3초 노출)",
    pv129c: "그린 부메랑 히트박스 25% 증가",
    pv129d: "이동속도 밸런스 (Red 빠름 > Green 중간 > Blue 보통)",
    pv129e: "훈련장 더미 3초 리스폰 + 킬로그 제거",
    pv129f: "로딩 화면 추가 + 무한 로딩 수정",
    pv129g: "다른 탭 전환 시에도 게임 진행",
    pv129h: "타이틀 Colors로 변경",
    pv129i: "HUD 로고 제거", pv129j: "봇 수풀 매복 시스템 제거",
    pv129k: "CSS 문법 오류 수정 (스타일 깨짐 해결)",
    pv129l: "Three.js CDN 복원 (로컬 로드 실패 대응)",
    pv128a: "알파 시즌 1 UI와 전투 경험 다듬기",
    pv128b: "캐릭터 카드 간소화 및 Orange 카드 개선",
    pv128c: "재장전 UI 개선 및 피격 이펙트 강화",
    pv128d: "킬 로그, 승률, 최고 기록 시스템 추가",
    pv127a: "로비 UI 개선: 선택된 캐릭터 강조, 배지, 애니메이션",
    pv127b: "캐릭터 정보 표시 강화",
    pv127c: "플레이어 정보 및 시즌 정보 개선",
    pv127d: "Orange Coming Soon 카드 추가",
    pv126a: "그린 공격 쿨다운 0.40 → 0.45",
    pv126b: "캐릭터 통계 표시 개선",
    pv126c: "사소한 버그 수정",
    pv125a: "그린 부메랑 투사체 피해 1000 → 900, 최대 피해 4000 → 3600",
    pv124a: "HUD 로고 제거", pv124b: "훈련장 더미 3초 후 자동 리스폰",
    pv124c: "훈련장 더미 사망 킬로그 제거", pv124d: "로딩 화면 추가 (진행 바 + 단계별 메시지)",
    pv124e: "무한 로딩 버그 수정", pv124f: "타이틀 Colors로 변경",
    pv124g: "다른 탭 전환 시에도 게임 계속 진행", pv124h: "봇 수풀 매복 시스템 제거",
    pv124i: "이동속도 밸런스 조정 (Red 빠름 > Green 중간 > Blue 보통)",
    pv124j: "그린 부메랑 투사체 히트박스 25% 증가",
    pv123a: "다국어 시스템 추가 (한국어/영어)",
    pv122a: "상성표 · 패치노트를 로비 우측 상단으로 이동",
    pv121a: "알파 시즌 1 시작", pv121b: "상성표 설명 텍스트 추가", pv121c: "패치노트 스크롤 수정",
    pv12a: "캐릭터별 승률 · 판수 · 승리 횟수 표시 추가",
    pv12b: "연승 시스템 추가 (2연승+1 ~ 5연승이상+4 보너스 트로피)",
    pv12c: "상성표 추가", pv12d: "패치노트 추가",
    pv11a: "즉시회복 시스템 변경 (3초 후 25% 일괄 회복, 봇은 5초)",
    pv11b: "봇 수풀 매복 영구 정지 버그 수정", pv11c: "자기장 피해 중 자연회복 동시 적용 차단",
    pv11d: "수풀 GPU 최적화", pv11e: "봇 타겟팅 로직 개선",
    pv10a: "3종 캐릭터 (Red / Green / Blue)", pv10b: "배틀 맵 3종 로테이션",
    pv10c: "트로피 · 순위 시스템", pv10d: "수풀 은신 메커닉", pv10e: "훈련장",
    // Chop Wood
    modeShowdown: "쇼다운", modeChopWood: "찹 우드", modeBack: "뒤로",
    chopWood: "찹 우드", startChopWood: "찹 우드 시작",
    cwTreeHP: "나무 HP", cwAxeLabel: "도끼",
    cwChopping: "벌목 중...",
    cwWin: "나무를 파괴했습니다!", cwLose: "나무가 파괴되었습니다...",
    cwChopDmg: "벌목 데미지: {0}", cwBestAxe: "최고 도끼: {0}", cwKills: "처치: {0}",
    cwTeamA: "아군 나무", cwTeamB: "적군 나무",
    cwRespawn: "리스폰까지 {0}초",
    axeWooden: "나무", axeStone: "돌", axeIron: "철", axeGold: "금",
    axeDiamond: "다이아", axeEmerald: "에메랄드", axeSapphire: "사파이어",
    axeRuby: "루비", axeAmethyst: "아메시스트", axeRainbow: "무지개",
    // Leaderboard & Stats
    statsBtn: "내 정보", statsBtnClose: "내 정보 닫기",
    leaderboardBtn: "리더보드", leaderboardBtnClose: "리더보드 닫기",
    lbTrophy: "🏆 트로피: {0}", lbTotalWinrate: "📊 총 승률: {0}% ({1}승 / {2}판)",
    lbBestStreak: "🔥 최고 연승: {0}", lbCharBest: "캐릭터별 최고 승률:",
    statsShowdown: "쇼다운 전적:", statsChopWood: "찹 우드 전적:",
    statsNoRecord: "-",
    charWinrate: "{0}% | {1}승/{2}판",
    electricAttack: "전기 사냥",
    spreadLineAttack: "알약 제압",
    poisonAttack: "독침/독병",
    yellowDesc: "전기 사냥꾼, 감전으로 적을 느리게 한다",
    cyanDesc: "알약 6연발, 넓은 범위 제압",
    purpleDesc: "독침과 독병을 교대로 사용하는 지속 피해 견제형",
    redDetails: "탱커 · 사거리 5 · 이동속도 매우 빠름",
    greenDetails: "암살자 · 사거리 6 · 이동속도 빠름",
    blueDetails: "장거리 딜러 · 사거리 16 · 이동속도 보통",
    orangeDetails: "데미지 딜러 · 사거리 8 · 이동속도 보통",
    yellowDetails: "감전 사냥꾼 · 사거리 8 · 이동속도 보통",
    cyanDetails: "컨트롤 파이터 · 사거리 8 · 이동속도 보통",
    purpleDetails: "포이즌 컨트롤러 · 사거리 12 · 이동속도 보통",
    statHp: "체력", statAtk: "공격", statRange: "사거리", statSpeed: "기동",
    pv140a: "Cyan 캐릭터 추가 — 컨트롤 파이터 (알약 6연발, 넓은 범위 제압)",
    pv140e: "Purple 캐릭터 추가 — 포이즌 컨트롤러 (독침/독병 교대 공격)",
    pv140b: "상성표 7캐릭터로 갱신",
    pv140c: "찹 우드 맵 세로 레이아웃으로 변경",
    pv140d: "전체 캐릭터 색상 통일",
    pv145a: "슬로우/독/피격 발광 전신(팔·다리 포함)에 적용",
    pv145b: "슬로우/독 발광색 개선 (하늘색 / 연두색)",
    pv145c: "봇 AI 경로 탐색 개선 — 벽·호수 우회 이동",
    pv145d: "클릭 공격 시 자동조준 추가 (가장 가까운 적 방향)",
    pv144a: "Purple 캐릭터 추가 — 포이즌 컨트롤러 (독침/독병 교대 공격)",
    pv144b: "스킨 시스템 추가 — Alpha Red 황금 왕관 한정 스킨",
    pv144c: "전 캐릭터 적중 이펙트 추가",
    pv144d: "Red 펀치 이펙트 강화 (충격파 링 + 버스트)",
    pv144e: "Yellow 감전 이펙트 강화 (번개선 4갈래 + 스파크)",
    pv144f: "슬로우/독 상태 이펙트 추가 (얼음 결정 / 독 거품)",
    pv144g: "Blue·Yellow·Purple 투사체 꼬리 이펙트 추가",
    pv144h: "수동 공격 시 자동조준 해제 + 탭 전환 프리즈 수정",
    pv143i: "Purple 캐릭터 추가 — 포이즌 컨트롤러 (독침/독병 교대 공격)",
    pv143a: "캐릭터 최대 레벨 Lv.6 추가 (비용 4000, 최대 +10%)",
    pv143b: "캐릭터 모델링 개선: 팔꿈치·무릎 관절 추가, 몸통 슬림화",
    pv143c: "Red 전용 가드 스탠스 + 강펀치 애니메이션",
    pv143d: "Yellow: 데미지 3400→2400, 사거리 8→12",
    pv143e: "Green: 부메랑 데미지 1100→950, 히트박스 +30%",
    pv143f: "Blue: 체력 4400→4800, 탄속 28→32",
    pv143g: "Orange: 직격 데미지 850→750",
    pv143h: "벽/호수와 겹치는 수풀 제거 (해골 협곡 9개, 마른 호수 3개)",
    pv142f: "Orange 추가 너프: 파편 데미지 400→300, 재장전 1.0→1.3초, 파편 범위 2.5→3.5",
    pv141a: "선택 캐릭터 강조 강화 (glow + 떠오르는 효과)",
    pv141b: "3D 캐릭터 프리뷰 150% 확대",
    pv141c: "좌측 패널에 스탯 바 추가 (체력/공격/사거리/기동)",
    pv141d: "레벨 옆에 시즌 + 버전 표시 추가",
    pv141e: "캐릭터 설명을 컬러 버튼 패널로 이동",
    pv139a: "Red 체력 9000→9800, 공격 쿨다운 0.62→0.55 버프",
    pv139b: "Orange 체력 6500→5800, 직격 데미지 1000→850 너프",
    pv139c: "Yellow 사거리 10→8, 감전 지속 2.0→1.5초 너프",
    pv138a: "캐릭터 모델링 개선: 어깨·허벅지 관절 추가",
    pv137a: "Yellow 캐릭터 추가 (전기 투사체 + 감전 감속)",
    pv137b: "상성표 5캐릭터 + 경합 열 추가",
    pv137d: "Yellow 사거리 8→10, 데미지 4400→3400",
    pv137e: "캐릭터 카드 실제 인게임 수치 동기화",
    pv137f: "리더보드 봇 이름 고정", pv137g: "Blue 아이콘 색상 수정",
    pv137c: "로비 왼쪽 캐릭터 컬러 버튼 추가",
  },
  en: {
    exitTraining: "Leave Training", survivorsLabel: "Survivors", zoneLabel: "Zone",
    zoneWaiting: "Waiting", ammoFull: "Ammo Full", ammoLabel: "Ammo", attack: "ATK",
    zoneWarning: "Outside the zone!", matchupBtn: "Matchups", matchupBtnClose: "Close Matchups",
    matchupDesc: "Rock-paper-scissors — target your advantage to win!",
    muChar: "Character", muAdv: "✅ Strong", muEven: "⚔ Even", muDis: "❌ Weak",
    patchnotesBtn: "Patch Notes", patchnotesBtnClose: "Close Notes",
    gameTitle: "Skull Creek", welcomeMsg: "Welcome to the Battle Royale arena.",
    idLabel: "User ID", nicknameLabel: "Nickname", idPlaceholder: "Max 16 chars",
    nickPlaceholder: "Max 12 chars", enterBattle: "Enter Arena",
    dailyLoginMsg: "Enter your ID for today.", dailyIdPlaceholder: "Enter ID",
    confirm: "Confirm", accountRecovery: "Account Recovery",
    season: "Alpha Season 3", charSelect: "Select Character", charCount: "7 Characters",
    redDesc: "Double Punch, close-range tank", greenDesc: "4-shot boomerang, mid-range",
    blueDesc: "Fast sniper, long range",
    orangeDesc: "Damage dealer, explosive spread",
    controls: "WASD Move · Mouse Aim · Click Attack · Auto Reload",
    startBattle: "Start Battle", training: "Training", playAgain: "Play Again", exit: "Exit",
    comingSoonDesc: "Coming in next season",
    trophyLabel: "Trophies", record: "{0}W {1}L", winrate: "WR {0}%  |  {1}W / {2}G",
    firstGame: "Play your first match!", streak: "🔥 {0} Win Streak",
    bestStreakLabel: "Best streak: {0}",
    nextAmmo: "Next {0}s", noAmmo: "No Ammo", stability: "Stability {0}%",
    doublePunch: "Double Punch", boomerang: "Boomerang", sniper: "Sniper", bombAttack: "Bomb Throw",
    mapPrefix: "Map: ", resultKO: "Eliminated", trainingKO: "Knocked out during training.",
    dmgDealt: "Damage Dealt: {0}", rank1: "#1 🏆", rankN: "#{0}",
    resultDead: "Eliminated. {0} trophies{1}", resultDraw: "Draw. {0} trophies{1}",
    resultWin: "Last one standing! {0} trophies{1}",
    resultLose: "{0} wins. {1} trophies{2}",
    streakAchieve: "🔥 {0} Win Streak!{1}", streakBonus: " (+{0} bonus)",
    streakBroken: "Streak broken (best: {0})",
    milestone100: "🎉 100 Wins! +50 Trophies\n",
    loginExceeded: "Too many login attempts.",
    loginWrong: "Incorrect ID.", loginRemain: "Incorrect ID. Remaining: {0}",
    myId: "My ID: {0}", totalTrophy: " (total {0})",
    killFeed: "{0} killed {1}",
    zonePhase1: "Phase 1", zonePhase2: "Phase 2", zonePhase3: "Phase 3",
    zonePhase4: "Phase 4", zoneFinal: "Final Zone",
    loadingLights: "Creating lights...", loadingMap: "Building map...",
    loadingTraining: "Setting up training...", loadingInput: "Configuring input...",
    loadingReady: "Getting ready...", loadingDone: "Done!",
    pv136a: "My Info + Leaderboard panels", pv136b: "AI random names (KR/EN/mixed)",
    pv136c: "Leaderboard bot user rankings", pv136d: "Per-season win rate tracking",
    pv136e: "Alpha Season 2 transition",
    pv136f: "Red HP 10K→9K, Green range 5→6, Orange bomb speed 14→16",
    pv136g: "Green boomerang 900→1100, Orange splash 1000→400",
    pv136h: "Green bot AI optimal range 3.5 tiles",
    pv135a: "Orange splash damage 10 → 1000 buff", pv135b: "Orange projectile hitbox x2",
    pv135c: "Red damage +10% (4000 → 4400)", pv135d: "Ammo UI not updating fix",
    pv134a: "Chop Wood zone damage removed", pv134b: "Chop Wood player movement unlocked",
    pv134c: "Tree HP 100 → 50", pv134d: "Chop interval 2s → 1s",
    pv133a: "Mode selector UI (Showdown/Chop Wood)",
    pv133b: "Chop Wood team markers (head color + kill feed color)",
    pv133c: "Red damage +10% (4000 → 4400)",
    pv132a: "Orange splash range 5 → 2.5 nerf", pv132b: "Red move speed +4% buff",
    pv132c: "Blue attack cooldown 0.25 → 0.3s nerf", pv132d: "Dead code cleanup (-1400 lines)",
    pv132e: "Chop Wood mode spec written",
    pv131a: "Orange aim indicator added", pv131b: "Matchup table updated to 4 characters",
    pv131c: "Removed objects outside zone on all 3 maps + border walls",
    pv131d: "Fixed victory screen not showing", pv131e: "Lobby UI width +25%",
    pv131f: "LANGS translation data separated to module", pv131g: "bestStreakLabel translation key added",
    pv130a: "Orange character added (bomb + 5-way explosion)",
    pv130b: "Zone color changed to green", pv130c: "Zone shrink time reduced (136s → 75s)",
    pv130d: "Damage taken shown as red popup", pv130e: "Orange range adjusted to 8 tiles",
    pv129a: "Bot AI improvements (targeting, zone awareness, per-char strategy)",
    pv129b: "Bush combat reveal system (3s exposure on attack/hit)",
    pv129c: "Green boomerang hitbox +25%",
    pv129d: "Move speed rebalance (Red fast > Green mid > Blue normal)",
    pv129e: "Training dummy 3s respawn + kill log removed",
    pv129f: "Loading screen + infinite loading fix",
    pv129g: "Game runs in background tabs",
    pv129h: "Title changed to Colors",
    pv129i: "HUD logo removed", pv129j: "Bot bush ambush system removed",
    pv129k: "CSS syntax error fix (broken styles)",
    pv129l: "Three.js CDN restored (local load fix)",
    pv128a: "Alpha Season 1 UI + combat polish",
    pv128b: "Simplified character cards + Orange card polish",
    pv128c: "Reload UI polish + hit feedback improvements",
    pv128d: "Kill log, win rate, best streak system added",
    pv127a: "Lobby UI improvements: selected character highlight, badge, animation",
    pv127b: "Enhanced character info display",
    pv127c: "Player info and season info improvements",
    pv127d: "Orange Coming Soon card added",
    pv126a: "Green attack cooldown 0.40 → 0.45",
    pv126b: "Improved character statistics display",
    pv126c: "Minor bug fixes",
    pv125a: "Green boomerang projectile damage 1000 → 900, max damage 4000 → 3600",
    pv124a: "HUD logo removed", pv124b: "Training dummy auto-respawn (3s)",
    pv124c: "Training dummy kill log removed", pv124d: "Loading screen (progress bar + messages)",
    pv124e: "Infinite loading fix", pv124f: "Title changed to Colors",
    pv124g: "Game runs in background tabs", pv124h: "Bot bush ambush system removed",
    pv124i: "Move speed rebalance (Red fast > Green mid > Blue normal)",
    pv124j: "Green boomerang hitbox +25%",
    pv123a: "Multi-language support (KR/EN)",
    pv122a: "Moved matchups & patch notes to top-right",
    pv121a: "Alpha Season 1 start", pv121b: "Matchup description added", pv121c: "Patch notes scroll fix",
    pv12a: "Per-character win rate / games / wins display",
    pv12b: "Win streak system (2-streak +1 ~ 5+ streak +4 bonus trophies)",
    pv12c: "Matchup table added", pv12d: "Patch notes added",
    pv11a: "Instant regen changed (25% lump after 3s, bots 5s)",
    pv11b: "Bot bush ambush freeze fix", pv11c: "Zone damage blocks natural regen",
    pv11d: "Bush GPU optimization", pv11e: "Bot targeting improvements",
    pv10a: "3 Characters (Red / Green / Blue)", pv10b: "3 Battle Map rotation",
    pv10c: "Trophy & ranking system", pv10d: "Bush stealth mechanic", pv10e: "Training mode",
    // Chop Wood
    modeShowdown: "Showdown", modeChopWood: "Chop Wood", modeBack: "Back",
    chopWood: "Chop Wood", startChopWood: "Start Chop Wood",
    cwTreeHP: "Tree HP", cwAxeLabel: "Axe",
    cwChopping: "Chopping...",
    cwWin: "You destroyed the tree!", cwLose: "Your tree was destroyed...",
    cwChopDmg: "Chop Damage: {0}", cwBestAxe: "Best Axe: {0}", cwKills: "Kills: {0}",
    cwTeamA: "Your Tree", cwTeamB: "Enemy Tree",
    cwRespawn: "Respawn in {0}s",
    axeWooden: "Wooden", axeStone: "Stone", axeIron: "Iron", axeGold: "Gold",
    axeDiamond: "Diamond", axeEmerald: "Emerald", axeSapphire: "Sapphire",
    axeRuby: "Ruby", axeAmethyst: "Amethyst", axeRainbow: "Rainbow",
    // Leaderboard & Stats
    statsBtn: "My Stats", statsBtnClose: "Close Stats",
    leaderboardBtn: "Leaderboard", leaderboardBtnClose: "Close Leaderboard",
    lbTrophy: "🏆 Trophies: {0}", lbTotalWinrate: "📊 Win Rate: {0}% ({1}W / {2}G)",
    lbBestStreak: "🔥 Best Streak: {0}", lbCharBest: "Best Win Rate by Character:",
    statsShowdown: "Showdown Record:", statsChopWood: "Chop Wood Record:",
    statsNoRecord: "-",
    charWinrate: "{0}% | {1}W/{2}G",
    electricAttack: "Electric Shot",
    spreadLineAttack: "Pill Barrage",
    poisonAttack: "Needle / Vial",
    yellowDesc: "Electric hunter that slows enemies with every hit",
    cyanDesc: "Fires 6 pills in a wide line to suppress enemies",
    purpleDesc: "Alternates poison needle and vial for sustained damage",
    redDetails: "Tank · Range 5 · Speed Very Fast",
    greenDetails: "Assassin · Range 6 · Speed Fast",
    blueDetails: "Sniper · Range 16 · Speed Normal",
    orangeDetails: "Damage Dealer · Range 8 · Speed Normal",
    yellowDetails: "Shock Hunter · Range 8 · Speed Normal",
    cyanDetails: "Control Fighter · Range 8 · Speed Normal",
    purpleDetails: "Poison Controller · Range 12 · Speed Normal",
    statHp: "HP", statAtk: "ATK", statRange: "Range", statSpeed: "Speed",
    pv140a: "Cyan character added — Control Fighter (6-pill spread line, wide area suppression)",
    pv140e: "Purple character added — Poison Controller (alternating needle/vial attacks)",
    pv140b: "Matchup table updated to 7 characters",
    pv140c: "Chop Wood map changed to vertical layout",
    pv140d: "Unified all character colors",
    pv145a: "Slow/poison/hit glow applied to full body (arms & legs)",
    pv145b: "Slow/poison glow colors improved (sky blue / lime green)",
    pv145c: "Bot AI pathfinding improved — wall & lake avoidance",
    pv145d: "Auto-aim on click attack added (nearest enemy direction)",
    pv144a: "Purple character added — Poison Controller (alternating needle/vial attacks)",
    pv144b: "Skin system added — Alpha Red golden crown limited skin",
    pv144c: "Hit effects added for all characters",
    pv144d: "Red punch effect enhanced (shockwave ring + burst)",
    pv144e: "Yellow electrocution effect enhanced (4-way lightning + sparks)",
    pv144f: "Slow/poison status effects added (ice crystal / poison bubbles)",
    pv144g: "Blue·Yellow·Purple projectile trail effects added",
    pv144h: "Manual attack auto-aim fix + tab switch freeze fix",
    pv143i: "Purple character added — Poison Controller (alternating needle/vial attacks)",
    pv143a: "Max character level Lv.6 added (cost 4000, up to +10%)",
    pv143b: "Character modeling improved: elbow & knee joints, slimmer torso",
    pv143c: "Red exclusive guard stance + power punch animation",
    pv143d: "Yellow: damage 3400→2400, range 8→12",
    pv143e: "Green: boomerang damage 1100→950, hitbox +30%",
    pv143f: "Blue: HP 4400→4800, bullet speed 28→32",
    pv143g: "Orange: direct hit damage 850→750",
    pv143h: "Removed bushes overlapping walls/lakes (Skull Canyon 9, Dry Lake 3)",
    pv142f: "Orange nerf: splash damage 400→300, reload 1.0→1.3s, splash range 2.5→3.5",
    pv141a: "Selected character highlight enhanced (glow + float effect)",
    pv141b: "3D character preview enlarged 150%",
    pv141c: "Stat bars added to left panel (HP/ATK/Range/Speed)",
    pv141d: "Season + version display next to level",
    pv141e: "Character details moved to color button panel",
    pv139a: "Red HP 9000→9800, attack cooldown 0.62→0.55 buff",
    pv139b: "Orange HP 6500→5800, direct damage 1000→850 nerf",
    pv139c: "Yellow range 10→8, shock duration 2.0→1.5s nerf",
    pv138a: "Character modeling improved: shoulder & thigh joints added",
    pv137a: "Yellow character added (electric projectile + shock slow)",
    pv137b: "Matchup table 5 chars + Even column",
    pv137d: "Yellow range 8→10, damage 4400→3400",
    pv137e: "Character card stats synced with in-game values",
    pv137f: "Leaderboard bot names fixed", pv137g: "Blue icon color fix",
    pv137c: "Character color buttons added to lobby left side",
  },
};
