const deg = (value) => value * (Math.PI / 180);

export const CHARACTERS = {
  red: {
    color: 0xff0000,
    maxHealth: 9800,
    attackType: "punch",
    reloadDuration: 0.5,
    attackCooldown: 0.55,
    moveSpeedMultiplier: 1.4,
    walk: { cycleSpeed: 9, armAmp: 0.34, legAmp: 0.40, armRestZ: Math.PI * 0.1 },
  },
  green: {
    color: 0x00ff00,
    maxHealth: 8400,
    attackType: "boomerang",
    reloadDuration: 0.5,
    attackCooldown: 0.45,
    moveSpeedMultiplier: 1.2,
    boomerangCount: 4,
    boomerangDamage: 950,
    boomerangRange: 8,
    boomerangSpeed: 20,
    boomerangReturnSpeedMultiplier: 1.1,
    boomerangFarThreshold: 3.5,
    boomerangFarMultiplier: 0.625,
    boomerangAngles: [-15, -5, 5, 15].map((d) => d * (Math.PI / 180)),
    walk: { cycleSpeed: 8, armAmp: 0.30, legAmp: 0.38, armRestZ: Math.PI * 0.06 },
  },
  blue: {
    color: 0x0000ff,
    maxHealth: 4800,
    attackType: "bullet",
    reloadDuration: 0.3,
    attackCooldown: 0.3,
    bulletDamage: 1500,
    bulletRange: 16,
    bulletSpeed: 32,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 7, armAmp: 0.20, legAmp: 0.34, armRestZ: Math.PI * 0.03 },
  },
  orange: {
    color: 0xffa500,
    maxHealth: 5800,
    attackType: "bomb",
    reloadDuration: 0.5,
    attackCooldown: 0.35,
    bombDamage: 900,
    bombSplashDamage: 700,
    bombRange: 9,
    bombSpeed: 26,
    bombSplashCount: 5,
    bombSplashSpeed: 10,
    bombSplashRange: 4.4,
    bombSplashHitRadius: 0.75,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  yellow: {
    color: 0xffff00,
    maxHealth: 5800,
    attackType: "electric",
    reloadDuration: 0.5,
    attackCooldown: 0.35,
    electricDamage: 2400,
    electricRange: 13,
    electricSpeed: 16,
    shockSlowPercent: 0.4,
    shockDuration: 1.5,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  cyan: {
    color: 0x0ff0fe,
    maxHealth: 6200,
    attackType: "spreadLine",
    reloadDuration: 0.5,
    attackCooldown: 0.35,
    spreadLineDamage: 600,
    spreadLineRange: 9.33,
    spreadLineSpeed: 18,
    spreadLineCount: 6,
    spreadLineSpacing: 0.75,
    ultimate: {
      name: "질풍 강타",
      damage: 800,
      range: 10,
      width: 10,
      speedMultiplier: 5 / 3,
      knockback: 8,
      chargeRequired: 12,
    },
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  purple: {
    color: 0x800080,
    maxHealth: 6000,
    attackType: "poison",
    reloadDuration: 0.5,
    attackCooldown: 0.45,
    needleRange: 14,
    needleSpeed: 18,
    needleDamage: 750,
    poisonDPS: 800,
    poisonDuration: 4,
    vialRange: 14,
    vialSpeed: 18,
    vialDamage: 3200,
    vialSplashRadius: 5.0,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 7, armAmp: 0.22, legAmp: 0.34, armRestZ: Math.PI * 0.04 },
  },
  pink: {
    color: 0xF4CDD3,
    maxHealth: 11500,
    attackType: "heal_circle",
    reloadDuration: 0.4,
    attackCooldown: 0.2,
    healCircleRange: 4.5,
    healCircleDamage: 2400,
    healCircleHeal: 2400,
    moveSpeedMultiplier: 1.4,
    walk: { cycleSpeed: 9, armAmp: 0.34, legAmp: 0.40, armRestZ: Math.PI * 0.1 },
  },
  crimson: {
    color: 0xa00000,
    maxHealth: 9800,
    attackType: "punchCombo",
    reloadDuration: 0.5,
    attackCooldown: 0.74,
    // 게임 내 최고 이동속도 — Pink/Red(1.4)보다 빠르다
    moveSpeedMultiplier: 1.5,
    attackRange: 3.5,
    attackDamage: 900,
    attackCount: 3,
    attackIntervalMs: 120,
    attackHalfAngle: deg(42),
    attackAngles: [-25, 0, 25].map(deg),
    ultimate: {
      name: "KO 스트레이트",
      damage: 2500,
      size: 5,
      knockback: 1,
      chargeRequired: 9,
    },
    walk: { cycleSpeed: 9, armAmp: 0.36, legAmp: 0.42, armRestZ: Math.PI * 0.1 },
  },
};
