const deg = (value) => value * (Math.PI / 180);

export const CHARACTERS = {
  red: {
    color: 0xff0000,
    maxHealth: 9800,
    attackType: "punch",
    reloadDuration: 0.9,
    attackCooldown: 0.55,
    attackRange: 5.5,
    ultimate: { name: "레드 가드", duration: 8, damageReduction: 0.6, chargeRequired: 7 },
    moveSpeedMultiplier: 1.4,
    walk: { cycleSpeed: 9, armAmp: 0.34, legAmp: 0.40, armRestZ: Math.PI * 0.1 },
  },
  green: {
    color: 0x00ff00,
    maxHealth: 8400,
    attackType: "boomerang",
    reloadDuration: 1.0,
    attackCooldown: 0.45,
    moveSpeedMultiplier: 1.2,
    boomerangCount: 4,
    boomerangDamage: 1000,
    boomerangRange: 7,
    boomerangSpeed: 20,
    boomerangReturnSpeedMultiplier: 1.1,
    boomerangReturnDamageMultiplier: 0.35,
    boomerangFarThreshold: 3.5,
    boomerangFarMultiplier: 0.625,
    boomerangAngles: [-15, -5, 5, 15].map((d) => d * (Math.PI / 180)),
    ultimate: {
      name: "은신 수풀",
      radius: 2.2,
      duration: 10,
      revealDuration: 3,
      chargeRequired: 7,
    },
    walk: { cycleSpeed: 8, armAmp: 0.30, legAmp: 0.38, armRestZ: Math.PI * 0.06 },
  },
  blue: {
    color: 0x0000ff,
    maxHealth: 4800,
    attackType: "bullet",
    reloadDuration: 0.5,
    attackCooldown: 0.3,
    bulletDamage: 1500,
    bulletRange: 16,
    bulletSpeed: 32,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 7, armAmp: 0.20, legAmp: 0.34, armRestZ: Math.PI * 0.03 },
  },
  orange: {
    color: 0xffa500,
    maxHealth: 5800,
    attackType: "bomb",
    reloadDuration: 1.0,
    attackCooldown: 0.35,
    bombDamage: 900,
    bombSplashDamage: 700,
    bombRange: 9,
    bombSpeed: 26,
    bombSplashCount: 5,
    bombDirectHitJuiceCount: 4,
    bombSplashSpeed: 10,
    bombSplashRange: 4.4,
    bombSplashHitRadius: 0.75,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  yellow: {
    color: 0xffff00,
    maxHealth: 5800,
    attackType: "electric",
    reloadDuration: 0.9,
    attackCooldown: 0.45,
    attackDelay: 0.12,
    electricDamage: 2200,
    electricRange: 12,
    electricSpeed: 16,
    shockSlowPercent: 0.25,
    shockDuration: 2,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  cyan: {
    color: 0x0ff0fe,
    maxHealth: 7200,
    attackType: "spreadLine",
    reloadDuration: 0.8,
    attackCooldown: 0.35,
    spreadLineDamage: 750,
    spreadLineRange: 8.33,
    spreadLineSpeed: 18,
    spreadLineCount: 6,
    spreadLineSpacing: 0.75,
    ultimate: {
      name: "질풍 강타",
      damage: 1300,
      range: 10,
      width: 10,
      speedMultiplier: 5 / 3,
      knockback: 8,
      chargeRequired: 6,
    },
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  purple: {
    color: 0x800080,
    maxHealth: 6000,
    attackType: "poison",
    reloadDuration: 1.1,
    attackCooldown: 0.45,
    needleRange: 14,
    needleSpeed: 18,
    needleDamage: 700,
    poisonDPS: 760,
    poisonDuration: 4,
    needleCount: 3,
    needleRadial: false,
    needleSpreadAngle: deg(24),
    vialRange: 11,
    vialSpeed: 18,
    vialDamage: 2700,
    vialSplashRadius: 4.0,
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 7, armAmp: 0.22, legAmp: 0.34, armRestZ: Math.PI * 0.04 },
  },
  pink: {
    color: 0xF4CDD3,
    maxHealth: 10500,
    attackType: "heal_circle",
    reloadDuration: 0.8,
    attackCooldown: 0.3,
    healCircleRange: 4.5,
    healCircleDamage: 2100,
    healCircleHeal: 1400,
    ultimate: { name: "앙코르!", reviveHealthRatio: 0.4, duration: 12, reviveDelay: 3, invulnerabilityDuration: 2, radius: 8, chargeRequired: 15 },
    moveSpeedMultiplier: 1.3,
    walk: { cycleSpeed: 9, armAmp: 0.34, legAmp: 0.40, armRestZ: Math.PI * 0.1 },
  },
  crimson: {
    color: 0xa00000,
    maxHealth: 9800,
    attackType: "punchCombo",
    reloadDuration: 0.9,
    attackCooldown: 0.74,
    // 게임 내 최고 이동속도 — Pink/Red(1.4)보다 빠르다
    moveSpeedMultiplier: 1.4,
    attackRange: 7,
    attackDamage: 4000 / 3,
    attackCount: 3,
    attackIntervalMs: 120,
    attackHalfAngle: deg(42),
    attackAngles: [-25, 0, 25].map(deg),
    ultimate: {
      name: "KO 스트레이트",
      damage: 3000,
      size: 6,
      knockback: 1,
      chargeRequired: 9,
    },
    walk: { cycleSpeed: 9, armAmp: 0.36, legAmp: 0.42, armRestZ: Math.PI * 0.1 },
  },
  gold: {
    color: 0xd4a928,
    maxHealth: 6200,
    attackType: "goldOre",
    reloadDuration: 1.2,
    attackCooldown: 0.8,
    moveSpeedMultiplier: 1.0,
    stage1Damage: 4000, stage1Range: 8, stage1Speed: 16, stage1Size: 2, stage1SplashRadius: 1.5,
    stage2Damage: 2000, stage2Range: 4, stage2Speed: 18,
    stage3Damage: 1000, stage3Range: 3, stage3Speed: 20,
    projectileRadius: 0.2, maxChargePerAttack: 6,
    ultimate: { name: "Malfunction Zone", damage: 0, radius: 3, duration: 4, delay: 0.35, chargeRequired: 12 },
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
  ivory: {
    color: 0xfffff0,
    maxHealth: 7200,
    attackType: "punch",
    reloadDuration: 1.3,
    attackCooldown: 0.65,
    iceCreamDamage: 1100,
    iceCreamRange: 10,
    iceCreamSpeed: 12,
    iceCreamZoneRadius: 2.8,
    iceCreamZoneDuration: 4,
    iceCreamZoneTickInterval: 1,
    ultimate: { name: "단체 주문", patternRadius: 3.2, castRange: 12, chargeRequired: 8 },
    moveSpeedMultiplier: 1.0,
    walk: { cycleSpeed: 7, armAmp: 0.24, legAmp: 0.34, armRestZ: Math.PI * 0.05 },
  },
  chartreuse: {
    color: 0x7fff00,
    maxHealth: 6200,
    attackType: "chartreuse",
    reloadDuration: 1.2,
    attackCooldown: 0.55,
    moveSpeedMultiplier: 1.0,
    chartreuseRange: 9.5,
    chartreuseSpeed: 22,
    chartreuseDamage: 1200,
    chartreuseEnhancedDamage: 2400,
    ultimate: { name: "49% 정신 차림", duration: 6, chargeRequired: 8 },
    walk: { cycleSpeed: 8, armAmp: 0.25, legAmp: 0.36, armRestZ: Math.PI * 0.05 },
  },
};
